# Generated by Django 5.0.2 on 2024-04-11 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAuth', '0009_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('observation_pic', models.ImageField(blank=True, null=True, upload_to='observation_pics/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuth.userprofile')),
            ],
        ),
    ]
