# Generated by Django 5.0.2 on 2024-04-13 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Identification', '0001_initial'),
        ('ObservationJournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userobservation',
            name='species',
            field=models.ForeignKey(default='- uknown species -', on_delete=django.db.models.deletion.CASCADE, to='Identification.snakespecies'),
        ),
    ]
