# Generated by Django 5.0.2 on 2024-04-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ObservationJournal', '0003_alter_userobservation_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userobservation',
            name='species',
        ),
    ]
