# Generated by Django 5.0.2 on 2024-04-13 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Identification', '0001_initial'),
        ('ObservationJournal', '0005_userobservation_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userobservation',
            name='species',
            field=models.ForeignKey(blank=True, default='Unsure', null=True, on_delete=django.db.models.deletion.CASCADE, to='Identification.snakespecies'),
        ),
    ]
