# Generated by Django 5.0.2 on 2024-04-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObservationJournal', '0008_alter_userobservation_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='userobservation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userobservation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
