# Generated by Django 5.0.2 on 2024-04-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='observations',
            field=models.IntegerField(default=0),
        ),
    ]
