# Generated by Django 5.0.2 on 2024-04-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0005_alter_userprofile_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilepic',
            new_name='profile_pic',
        ),
    ]
