# Generated by Django 5.0.2 on 2024-04-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Identification', '0001_initial'),
        ('UserAuth', '0009_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_species',
            field=models.ManyToManyField(blank=True, to='Identification.snakespecies'),
        ),
    ]
