# Generated by Django 5.0.2 on 2024-04-30 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Identification', '0001_initial'),
        ('UserAuth', '0011_remove_userprofile_favorite_species_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Identification.snakespecies'),
        ),
    ]
